common:
  random_seed: 2020
  ssl_algo:
    label_propagation : label_propagation_cached.LabelPropagationCached
    label_spreading : sklearn.semi_supervised.LabelSpreading
  labelled_proportion:
    - 0.05
    - 0.15
    - 0.25
  flip_budget_proportion:
    - 0 
    - 0.05
    - 0.10
    - 0.15
    - 0.2


datasets:
 cifar:
   gamma: 0.1
   iter: 5
   loader_function: cifarBinary_prep

 mnist:
   gamma: 5
   iter: 5
   loader_function: mnist17_prep

 rcv1:
   gamma: 20
   iter: 5
   loader_function: rcv_prep